const vj = document.getElementById('vj')
const rathod = document.getElementById('rathod')
const number = document.getElementById('number')
const email = document.getElementById('email')
const password = document.getElementById('password')
const password2 = document.getElementById('password2')
const check = document.getElementById('check')
const sign = document.getElementById('sign')